QUESTIONS: dict[str, list[str]] = {
    "python": [
        "What's Python's GIL and how does it affect multi-threaded ML training code? How would you work around it?",
        "Explain the difference between multiprocessing, threading, and asyncio for data loading pipelines. When would you choose each?",
        "How does Python's garbage collector work? What are reference cycles and how can they cause memory leaks in a training loop?",
        "Explain generators and the yield keyword. How would you use them to build a lazy data pipeline for a dataset that doesn't fit in memory?",
        "What's the difference between deepcopy and copy? Give a concrete example where using the wrong one breaks a model's state.",
        "Explain Python's __slots__. When would you use them in a DS codebase and what are the trade-offs?",
        "What are context managers and how do you implement a custom one? Give an example for managing GPU memory or timing a forward pass.",
        "Explain decorators with arguments. Write a retry decorator for a flaky API call that uses exponential backoff.",
        "What's the difference between staticmethod, classmethod, and regular instance methods? When does sklearn use classmethods?",
        "How does Python pickling work? Why does it matter for model serialization, and what are its limitations with lambdas and local functions?",
        "Explain abstract base classes (ABC). How does sklearn's BaseEstimator use them, and what methods must a custom estimator implement?",
        "What are Python's memory profiling tools? Walk me through how you'd find a memory leak in a training loop.",
        "Explain how __repr__ and __str__ differ. Why does a well-implemented __repr__ matter for debugging custom ML objects?",
        "What's the difference between a list comprehension and map/filter in terms of performance and readability? When would you use each?",
        "Explain how Python's import system works. What's the difference between a package and a module, and how does circular import happen?",
    ],
    "classical_ml": [
        "Explain the bias-variance tradeoff geometrically. How do you diagnose high bias vs high variance from learning curves?",
        "How does XGBoost differ from vanilla gradient boosting? What specific engineering decisions make it faster and more regularized?",
        "Explain L1 vs L2 regularization geometrically. When would you prefer L1 for a sparse feature space?",
        "What happens to OLS estimates when features are highly correlated? How do you detect multicollinearity and what do you do about it?",
        "Explain SVM's kernel trick. What does it mean to implicitly compute dot products in a high-dimensional feature space?",
        "Why does k-means fail on non-convex clusters? Name two algorithms that handle this and explain how they differ.",
        "Explain the EM algorithm. What ML models use it as their fitting procedure, and what can go wrong with convergence?",
        "What's the curse of dimensionality? Give a concrete example showing how it breaks nearest-neighbor classifiers as dimensions grow.",
        "How does Random Forest reduce variance compared to a single decision tree? What's the role of feature subsampling at each split?",
        "Explain the difference between ROC-AUC and precision-recall AUC. When does ROC-AUC give a misleadingly optimistic picture?",
        "What's stratified k-fold and when does regular k-fold give misleading results? Give an example with imbalanced classes.",
        "Compare SMOTE, class weights, and undersampling for class imbalance. What are the trade-offs in terms of overfitting and runtime?",
        "How do SHAP values work at a high level? What's the difference between SHAP and LIME in terms of locality and consistency?",
        "What's the difference between bagging and boosting theoretically? Give conditions under which each approach outperforms the other.",
        "Compare information gain and Gini impurity for decision tree splits. Does the choice of criterion materially affect tree quality?",
    ],
    "deep_learning": [
        "What problem does batch normalization solve? Where should BatchNorm be placed relative to activation functions, and why does it depend on the architecture?",
        "Explain vanishing gradients in deep networks. How do residual connections address this, and what does the gradient flow look like mathematically?",
        "Compare Adam and SGD with momentum. Under what conditions does SGD generalize better than Adam?",
        "Explain dropout as a regularizer. Why is it disabled at inference, and what's the connection to ensemble methods?",
        "What's the difference between depthwise separable convolutions and standard convolutions? How do they reduce parameter count?",
        "Walk me through the transformer's multi-head self-attention mechanism. What's the computational complexity and how does it scale with sequence length?",
        "What's gradient clipping and when is it necessary? How do you choose the clipping threshold in practice?",
        "How does learning rate warmup work in transformer training? What problem does it solve in the early steps?",
        "Explain mixed precision training with fp16/bf16. What numerical issues arise and how does loss scaling address them?",
        "What's the difference between data parallelism and model parallelism? When would you need tensor parallelism?",
        "Explain Xavier and He weight initialization. Why does the choice of initialization scheme depend on the activation function?",
        "What's knowledge distillation? Write out the loss function and explain what temperature controls.",
        "How does early stopping work as regularization? What metric do you monitor, and why is it important to use a separate validation set?",
        "Explain the difference between 1D, 2D, and 3D convolutions. Give a concrete use case for each dimensionality.",
        "What's the fundamental difference between generative and discriminative models? Give examples and explain which is harder to train and why.",
    ],
    "nlp_cv": [
        "Compare BPE, WordPiece, and SentencePiece tokenization. What trade-offs do they make between vocabulary size and OOV handling?",
        "What's the architectural difference between BERT and GPT? Why is BERT better for classification and GPT better for generation?",
        "Explain cross-entropy loss for language modeling. How is perplexity derived from it and what does a perplexity of 50 mean intuitively?",
        "What's positional encoding in transformers? When are learned positional embeddings better than fixed sinusoidal ones?",
        "Explain IoU and how it's used to compute mAP for object detection. What's the role of the IoU threshold in the calculation?",
        "What's the difference between semantic, instance, and panoptic segmentation? Give a real-world use case where the distinction matters.",
        "How does CLIP work? Describe the training objective and explain why it enables zero-shot classification.",
        "What image augmentation strategies prevent data leakage into validation? Give an example where a naive augmentation pipeline overfits.",
        "What's the difference between seq2seq with Bahdanau attention and a standard encoder-decoder transformer?",
        "How does beam search work? What's the trade-off between beam width and output quality, and what's the exposure bias problem?",
        "Explain label smoothing. When does it help, and can it ever hurt performance?",
        "Compare anchor-based detectors (Faster R-CNN, YOLO) with anchor-free ones (FCOS, CenterNet). What problem do anchor-free methods solve?",
        "How does in-context learning (few-shot prompting) work mechanistically? What are its failure modes compared to fine-tuning?",
        "Explain the role of KV cache in autoregressive generation. How does it reduce compute, and what's the memory trade-off?",
        "What's catastrophic forgetting in fine-tuning? How does LoRA reduce it, and what does the low-rank assumption mean geometrically?",
    ],
}
